### ISSUE TITLE
expression 용어 번역 통일

### ISSUE THREAD

**Issue by dakeshi** [golangkorea/golang-spec#154]
### 체크리스트
- [x] [번역 가이드 라인](https://github.com/golangkorea/golang-spec#번역-가이드라인) 문서는 읽어보셨나요? 

### Issue 설명(선택사항)
expression에 대한 번역 용어 통일과 관련해서 다음과 같이 검토했습니다.

번역 가능한 용어로는 `식`, `표현`, `표현식` 등이 있습니다. 주요 의견으로는

대부분의 문서에서 expression은 `식`으로 번역하고 있습니다. 현재 용어집에는 `index expression = 인덱스 표현` 으로 추가된 상태입니다. - @dakeshi

프로그래밍/수학을 배경으로 두고 개념을 생각했을 때 substitution이나 evaluation 과정을 거쳐서 결국 어떤 값으로 귀결되는 "식"이라는 뜻으로 사람들에게 보편적으로 받아들여지고 있다고 봅니다. - @jhonghee 

따라서, 가장 보편적으로 사용되는 `식`으로 번역하는 것이 좋다고 생각합니다.

### TODO

- [x] expression과 관련된 기존 번역문 확인해서 `식`으로 통일
- [x] expression을 용어집에 추가.  index expression은 용어집에서 삭제하거나 expression에 대한 예제로 부가설명. `인덱스 식`
